# Generated by Django 4.2.19 on 2025-05-01 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specs', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_new', models.BooleanField(default=True)),
                ('current_kilometer', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('rent_per_day', models.IntegerField()),
                ('is_rented', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('rent_per_week', models.IntegerField()),
                ('rent_per_month', models.IntegerField()),
                ('img', models.ImageField(max_length=500, upload_to='imgs/product')),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.car_model')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
    ]
