# Generated by Django 4.2.19 on 2025-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_description_product_features_car_model_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(max_length=500, null=True, upload_to='imgs/product'),
        ),
    ]
