# Generated by Django 4.2.19 on 2025-05-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='car_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.car_model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default=None, max_length=500, null=True, upload_to='imgs/product'),
        ),
    ]
