# Generated by Django 4.2.19 on 2025-05-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_review_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='review',
        ),
    ]
